In [1]:
import os
import json
import pandas as pd
import http.client 
from dotenv import load_dotenv
from sqlalchemy import create_engine

load_dotenv()

True

In [2]:
#connect to API
conn = http.client.HTTPSConnection("api.collectapi.com")

headers = {
    'content-type': "application/json",
    'authorization': os.getenv("GAS_API_KEY")
    }

#request data
conn.request("GET", "/gasPrice/stateUsaPrice?state=WA", headers=headers)

#read response
res = conn.getresponse()
data = res.read()

print(data.decode("utf-8"))

{"success":true,"result":{"state":[{"currency":"usd","name":"Washington","lowername":"washington","gasoline":"5.3620","midGrade":"5.6450","premium":"5.8990","diesel":"6.2640"}],"cities":[{"currency":"usd","gasoline":"5.1920","midGrade":"5.4440","premium":"5.7270","diesel":"5.9580","name":"Bellingham","lowername":"bellingham"},{"currency":"usd","gasoline":"5.5670","midGrade":"5.8090","premium":"6.0620","diesel":"6.3480","name":"Bremerton","lowername":"bremerton"},{"currency":"usd","gasoline":"5.3250","midGrade":"5.6110","premium":"5.8840","diesel":"6.4330","name":"Olympia","lowername":"olympia"},{"currency":"usd","gasoline":"5.0210","midGrade":"5.3310","premium":"5.5700","diesel":"5.9120","name":"Richland-Kennewick-Pasco","lowername":"richland-kennewick-pasco"},{"currency":"usd","gasoline":"5.6680","midGrade":"5.9160","premium":"6.1470","diesel":"6.5610","name":"Seattle-Bellevue-Everett","lowername":"seattle-bellevue-everett"},{"currency":"usd","gasoline":"4.8410","midGrade":"5.1120","premium":"5.3910","diesel":"5.8900","name":"Spokane","lowername":"spokane"},{"currency":"usd","gasoline":"5.4710","midGrade":"5.6990","premium":"5.9610","diesel":"6.4930","name":"Tacoma","lowername":"tacoma"},{"currency":"usd","gasoline":"5.0400","midGrade":"5.3420","premium":"5.6020","diesel":"5.9310","name":"Yakima","lowername":"yakima"},{"currency":"usd","gasoline":"5.2410","midGrade":"5.4770","premium":"5.7020","diesel":"6.0620","name":"Vancouver","lowername":"vancouver"},{"currency":"usd","gasoline":"4.7660","midGrade":"0.0000","premium":"5.0990","diesel":"5.2990","name":"Clarkson","lowername":"clarkson"},{"currency":"usd","gasoline":"5.2680","midGrade":"5.5180","premium":"5.8290","diesel":"6.0030","name":"Longview","lowername":"longview"},{"currency":"usd","gasoline":"5.1640","midGrade":"5.3860","premium":"5.6390","diesel":"6.0260","name":"Mount Vernon-Anacortes","lowername":"mount vernon-anacortes"},{"currency":"usd","gasoline":"5.2090","midGrade":"5.6120","premium":"5.7810","diesel":"6.2530","name":"Walla Walla","lowername":"walla walla"},{"currency":"usd","gasoline":"4.9200","midGrade":"5.1580","premium":"5.4660","diesel":"5.9580","name":"Wenatchee","lowername":"wenatchee"}]}}

In [3]:
#convert from bytes to dict
data_string = data.decode("utf-8")
print(type(data_string))
data_dict = json.loads(data_string)
type(data_dict)

<class 'str'>

dict

In [4]:
#extract cities 
city_data = data_dict["result"]["cities"]

#convert to a dataframe
city_df = pd.DataFrame(city_data)

In [5]:
city_df.head()

,currency,gasoline,midGrade,premium,diesel,name,lowername
0,usd,5.1920,5.4440,5.7270,5.9580,Bellingham,bellingham
1,usd,5.5670,5.8090,6.0620,6.3480,Bremerton,bremerton
2,usd,5.3250,5.6110,5.8840,6.4330,Olympia,olympia
3,usd,5.0210,5.3310,5.5700,5.9120,Richland-Kennewick-Pasco,richland-kennewick-pasco
4,usd,5.6680,5.9160,6.1470,6.5610,Seattle-Bellevue-Everett,seattle-bellevue-everett

In [6]:
#drop lowername column
city_df = city_df.drop(columns=["lowername"])
city_df.head()

  currency gasoline midGrade premium  diesel                      name
0      usd   5.1920   5.4440  5.7270  5.9580                Bellingham
1      usd   5.5670   5.8090  6.0620  6.3480                 Bremerton
2      usd   5.3250   5.6110  5.8840  6.4330                   Olympia
3      usd   5.0210   5.3310  5.5700  5.9120  Richland-Kennewick-Pasco
4      usd   5.6680   5.9160  6.1470  6.5610  Seattle-Bellevue-Everett

In [7]:
#rename name to cities
city_df.rename(columns={"name": "cities"}, inplace=True)
city_df.head()

  currency gasoline midGrade premium  diesel                    cities
0      usd   5.1920   5.4440  5.7270  5.9580                Bellingham
1      usd   5.5670   5.8090  6.0620  6.3480                 Bremerton
2      usd   5.3250   5.6110  5.8840  6.4330                   Olympia
3      usd   5.0210   5.3310  5.5700  5.9120  Richland-Kennewick-Pasco
4      usd   5.6680   5.9160  6.1470  6.5610  Seattle-Bellevue-Everett